theme: jekyll-theme-slate
title: IoPT App
description: We are here to improve the SoHo security a bit!
google_analytics: G-MK0E8ELDR7
show_downloads: true
github:
  zip_url: http://example.com/download.zip
